{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tresor.serviceAccountName" . }}
  labels: {{- include "tresor.labels" . | nindent 4 }}
  {{- $ann := deepCopy (.Values.serviceAccount.annotations | default dict) }}
  {{- if and .Values.workloadIdentity.enabled .Values.workloadIdentity.clientId }}
  {{- $_ := set $ann "azure.workload.identity/client-id" .Values.workloadIdentity.clientId }}
  {{- end }}
  {{- with $ann }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ include "tresor.usesAPI" . | eq "true" }}
{{- end }}
